/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SistemClassAndMain.GameSys;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Burcu
 */
public class GameFrame extends javax.swing.JFrame {

    DisplayFrame df = new DisplayFrame();
    SearchFrame sf = new SearchFrame();

    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gameIdLabel = new javax.swing.JLabel();
        publishedYearLabel = new javax.swing.JLabel();
        gameCategoryLabel = new javax.swing.JLabel();
        gameIdTF = new javax.swing.JTextField();
        publisheedYearTF = new javax.swing.JTextField();
        gameCategoryTF = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        burnedCalLabel = new javax.swing.JLabel();
        burnedCalTF = new javax.swing.JTextField();
        burnedCalLabel1 = new javax.swing.JLabel();
        point_TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispTA = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Frame");

        gameIdLabel.setText("Game Id:");

        publishedYearLabel.setText("Publiched Year:");

        gameCategoryLabel.setText("Game Category:");

        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        displayButton.setText("DISPLAY");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        burnedCalLabel.setText("Burnned Calories:");

        burnedCalLabel1.setText("Point:");

        dispTA.setColumns(20);
        dispTA.setRows(5);
        jScrollPane1.setViewportView(dispTA);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publishedYearLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gameIdLabel)
                            .addComponent(gameCategoryLabel)
                            .addComponent(burnedCalLabel)
                            .addComponent(burnedCalLabel1)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(burnedCalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(publisheedYearTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(gameCategoryTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(gameIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(point_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameIdLabel)
                            .addComponent(gameIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publishedYearLabel)
                            .addComponent(publisheedYearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameCategoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameCategoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(burnedCalLabel)
                            .addComponent(burnedCalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(burnedCalLabel1)
                            .addComponent(point_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton)
                            .addComponent(displayButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(clearButton))
                        .addGap(31, 31, 31))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        if (gameIdTF.getText().equals("") || publisheedYearTF.getText().equals("")
                || gameCategoryTF.getText().equals("") || burnedCalTF.getText().equals("")
                || point_TF.getText().equals("")) {

            dispTA.setText("Fill the necessary fields");
        } else {

            boolean res = GameSys.addToGameSet(Integer.parseInt(gameIdTF.getText()), Integer.parseInt(publisheedYearTF.getText()),
                    gameCategoryTF.getText(), Double.parseDouble(burnedCalTF.getText()), Double.parseDouble(point_TF.getText()));
            if (res) {
                dispTA.setText("Game is added");
            } else {
                dispTA.setText("A game with the same id already exists in the system");
            }

        }

        sf.getGameIdCMB().setModel(new DefaultComboBoxModel(GameSys.getGameId()));

    }//GEN-LAST:event_AddButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        if (GameSys.getGame().isEmpty()) {
            dispTA.setText("Set is empty");
        } else {
            df.setVisible(true);
            df.setDispTA(GameSys.displayGamesByCategory());
        }
    }//GEN-LAST:event_displayButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (GameSys.getGame().isEmpty()) {
            dispTA.setText("Set is empty");
        } else {
            sf.setVisible(true);
            sf.setDispTA(GameSys.search(Integer.parseInt(GameSys.getGameId()[0])).toString());
            sf.getGameIdCMB().setModel(new DefaultComboBoxModel(GameSys.getGameId()));
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        gameIdTF.setText("");
        publisheedYearTF.setText("");
        gameCategoryTF.setText("");
        burnedCalTF.setText("");
        point_TF.setText("");
        dispTA.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel burnedCalLabel;
    private javax.swing.JLabel burnedCalLabel1;
    private javax.swing.JTextField burnedCalTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea dispTA;
    private javax.swing.JButton displayButton;
    private javax.swing.JLabel gameCategoryLabel;
    private javax.swing.JTextField gameCategoryTF;
    private javax.swing.JLabel gameIdLabel;
    private javax.swing.JTextField gameIdTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField point_TF;
    private javax.swing.JLabel publishedYearLabel;
    private javax.swing.JTextField publisheedYearTF;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

}
