/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import SistemClassAndMain.*;
import SocialMediaHasA.*;
import java.util.ArrayList;
import SocialMediaInheritance.*;

/**
 *
 * @author Leyla
 */
public class FacebookAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form FacebookAccountFrame
     */
    public FacebookAccountFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(350,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreate = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        numOfFriends = new javax.swing.JLabel();
        txtFriends = new javax.swing.JTextField();
        lblEventInfo = new javax.swing.JLabel();
        lblEventId = new javax.swing.JLabel();
        txtEventId = new javax.swing.JTextField();
        lblEventName = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnAddAcc = new javax.swing.JButton();
        lblUrl = new javax.swing.JLabel();
        lblAddAccount = new javax.swing.JLabel();
        lblImageFace = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facebook Account");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreate.setText("Create a new account:");
        getContentPane().add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 20));

        lblName.setText("Enter name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, 20));

        lblSurname.setText("Enter surname:");
        getContentPane().add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 20));
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        numOfFriends.setText("Number Of Friends:");
        getContentPane().add(numOfFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 20));
        getContentPane().add(txtFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 20));

        lblEventInfo.setText("Enter Event Information:");
        getContentPane().add(lblEventInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 30));

        lblEventId.setText("Event ID:");
        getContentPane().add(lblEventId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtEventId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, -1));

        lblEventName.setText("Name:");
        getContentPane().add(lblEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, 20));
        getContentPane().add(txtEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 180, -1));

        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, 20));

        btnAddAcc.setText("ADD ACCOUNT");
        btnAddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));
        getContentPane().add(lblUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 300, 20));
        getContentPane().add(lblAddAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        lblImageFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facebook.png"))); // NOI18N
        getContentPane().add(lblImageFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, 250));

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccActionPerformed
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String url = SocialMediaAccountSys.createUrl(name,surname,"facebook");
        lblUrl.setText(url);
        int numOfFriends = Integer.parseInt(txtFriends.getText());
        int eventID = Integer.parseInt(txtEventId.getText());
        String nameEvent = txtEventName.getText();
        String date = txtDate.getText();
        ArrayList<Events> temp = new ArrayList();
        Events event = new Events(eventID,nameEvent,date);
        temp.add(event);
        FacebookAccount faceacc = new FacebookAccount("facebook", url, 2019, numOfFriends, 1, temp);
        lblAddAccount.setText(name+" "+surname+" is added");
        SocialMediaAccountSys.accountList.add(faceacc);
    }//GEN-LAST:event_btnAddAccActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
           dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAcc;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAddAccount;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEventId;
    private javax.swing.JLabel lblEventInfo;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblImageFace;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel numOfFriends;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEventId;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtFriends;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
