import pandas as pd
import numpy as np
gdp13=pd.read_excel('docs/education_gdp_2013.xlsx')
gdp14=pd.read_excel('docs/education_gdp_2014_15.xlsx')
print('2013 Data:')
print(gdp13)
print()
print('2014-15 Data:')
print(gdp14)
print()
dfJoin = pd.merge(left = gdp13, right = gdp14, left_on = 'Country Name', right_on = 'Country Name')
print('Merged Data Set:')
print(dfJoin)
print()
print('Data Set after Replace:')
dfJoin=dfJoin.replace('..',np.NaN)
print(dfJoin)
print()
print('Data Set after dropping NaN:')
cleanDf=dfJoin.dropna()
print(cleanDf)
print()
print('Data Set with Mean:')
cleanDf['Mean 2013-2015']=np.mean(cleanDf,axis=1)
print(cleanDf)
print()
print('Sorted by Mean:')
sortedDf=cleanDf.sort_values('Mean 2013-2015')
print(sortedDf)
