/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmallmain;

import java.util.ArrayList;

/**
 *
 * @author Leyla
 */
public class AddShoppingMallFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAgencyFrame
     */
    public AddShoppingMallFrame(ShoppingFrame a) {
        setSize(400,650);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPark = new javax.swing.JLabel();
        txtNumOfPark = new javax.swing.JTextField();
        lblClosedHour = new javax.swing.JLabel();
        txtClosedHour = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblIntroduction = new javax.swing.JLabel();
        lbl3shop = new javax.swing.JLabel();
        lblShopName1 = new javax.swing.JLabel();
        txtShop1Name = new javax.swing.JTextField();
        lblShopName2 = new javax.swing.JLabel();
        txtShop2Name = new javax.swing.JTextField();
        lblShopName3 = new javax.swing.JLabel();
        txtShop3Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Shopping Mall Frame");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setText("ID:");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 40, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, 30));

        lblName.setText("Name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 30));

        lblAddress.setText("Address:");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));

        lblPark.setText("Number Of Park:");
        getContentPane().add(lblPark, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(txtNumOfPark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 30));

        lblClosedHour.setText("Closed Hour:");
        getContentPane().add(lblClosedHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(txtClosedHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 30));
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 180, 20));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        lblIntroduction.setText("Adding New Shopping Mall");
        getContentPane().add(lblIntroduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, -1));

        lbl3shop.setText("Enter 3 shop information");
        getContentPane().add(lbl3shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblShopName1.setText("Shop1 Name:");
        getContentPane().add(lblShopName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, -1));
        getContentPane().add(txtShop1Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 200, 30));

        lblShopName2.setText("Shop 2 Name:");
        getContentPane().add(lblShopName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, -1));
        getContentPane().add(txtShop2Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 200, 30));

        lblShopName3.setText("Shop 3 Name:");
        getContentPane().add(lblShopName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 10));
        getContentPane().add(txtShop3Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String id = txtID.getText();
        String name = txtName.getText();
        String address = txtAddress.getText();
        int numOfPark = Integer.parseInt(txtNumOfPark.getText());
        double closedHour = Double.parseDouble(txtClosedHour.getText());
        ArrayList<String> temp = new ArrayList();
        String shop1 = txtShop1Name.getText();
        String shop2 = txtShop2Name.getText();
        String shop3 = txtShop3Name.getText();
        temp.add(shop1);
        temp.add(shop2);
        temp.add(shop3);
        ShoppingMall sm1 = new ShoppingMall(id, name, address, numOfPark, closedHour,temp);
        boolean check = ShoppingSys.addShoppingMall(sm1);
        if(check==true)
            lblInfo.setText("Mall added");
        else
            lblInfo.setText("Mall already exist!");
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lbl3shop;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblClosedHour;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblIntroduction;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPark;
    private javax.swing.JLabel lblShopName1;
    private javax.swing.JLabel lblShopName2;
    private javax.swing.JLabel lblShopName3;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtClosedHour;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumOfPark;
    private javax.swing.JTextField txtShop1Name;
    private javax.swing.JTextField txtShop2Name;
    private javax.swing.JTextField txtShop3Name;
    // End of variables declaration//GEN-END:variables
}
