/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmallmain;

import javax.swing.JComboBox;

/**
 *
 * @author Leyla
 */
public class ShoppingMallSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form AgencySearchFrame
     */
    public ShoppingMallSearchFrame(ShoppingFrame af) {
        setLocationRelativeTo(null);
        initComponents();
    }

    public JComboBox getCmbID() {
        return cmbID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbID = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearch = new javax.swing.JTextArea();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Shopping Mall Frame");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cmbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        txtSearch.setColumns(20);
        txtSearch.setRows(5);
        jScrollPane1.setViewportView(txtSearch);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 150));

        lblId.setText("Shopping Mall ID:");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(ShoppingSys.arr.isEmpty())
        {
            txtSearch.setText("First fill the arraylist");
        }
        else
        {
            String id = cmbID.getSelectedItem().toString();
            ShoppingMall temp = ShoppingSys.searchShoppingMall(id);
            txtSearch.setText(temp.toString());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextArea txtSearch;
    // End of variables declaration//GEN-END:variables
}
