/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingmallmain;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Leyla
 */
public class ShoppingFrame extends javax.swing.JFrame {

    AddShoppingMallFrame add = new AddShoppingMallFrame(this);
    ShoppingMallSearchFrame search = new ShoppingMallSearchFrame(this);
    DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
    public ShoppingFrame() {
       
        setSize(700,900);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        txtAreaAgency = new javax.swing.JScrollPane();
        txtShoppingArea = new javax.swing.JTextArea();
        btnRead = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Frame");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setText("Shopping Mall Info:");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        txtShoppingArea.setColumns(20);
        txtShoppingArea.setRows(5);
        txtAreaAgency.setViewportView(txtShoppingArea);

        getContentPane().add(txtAreaAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 220));

        btnRead.setText("READ FILE CONTENT");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, 30));

        btnAdd.setText("ADD Shopping MALL");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 150, 30));

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 150, 30));

        btnDisplay.setText("DISPLAY");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        ShoppingSys.readTxt("shopping.txt");
        txtShoppingArea.setText("File is read");
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        if(ShoppingSys.arr.isEmpty())
            txtShoppingArea.setText("ArrayList is empty");
        else
            txtShoppingArea.setText(ShoppingSys.display());
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        ArrayList arr = new ArrayList();
        search.getCmbID().removeAllItems();
        for (int i = 0; i < ShoppingSys.arr.size(); i++) {
          ShoppingMall sm = ShoppingSys.arr.get(i);
          dcm.addElement(sm.getId());
        }
        search.getCmbID().setModel(dcm);
        search.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JScrollPane txtAreaAgency;
    private javax.swing.JTextArea txtShoppingArea;
    // End of variables declaration//GEN-END:variables
}
